// Travels with Charley - Complete Route Data
// Extracted from the book by John Steinbeck (1962)
// Journey: Late September - Late December 1960, ~10,000 miles

const ROUTE_DATA = {
  meta: {
    title: "Travels with Charley: In Search of America",
    titleCn: "横越美国：追寻美国",
    author: "John Steinbeck 约翰·斯坦贝克",
    year: 1960,
    distance: "~10,000 miles / ~16,000 km",
    duration: "Late September - Late December 1960",
    vehicle: "GMC pickup truck with camper top, named Rocinante (罗西南特)",
    companion: "Charley (查理), a blue-gray Standard Poodle"
  },

  parts: [
    { id: 1, title: "Part One 第一部分", subtitle: "出发前的准备", color: "#2E86AB" },
    { id: 2, title: "Part Two 第二部分", subtitle: "新英格兰到中西部", color: "#A23B72" },
    { id: 3, title: "Part Three 第三部分", subtitle: "西部与太平洋海岸", color: "#F18F01" },
    { id: 4, title: "Part Four 第四部分", subtitle: "德州、深南与归途", color: "#C73E1D" }
  ],

  // Key people / vehicle - external image links (no download, all Wikipedia Commons)
  heroCards: [
    {
      key: "steinbeck",
      nameCn: "约翰·斯坦贝克",
      nameEn: "John Steinbeck",
      caption: "1962 年获诺贝尔文学奖时的斯坦贝克，大胡子，戴海军帽。出发时 58 岁。",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/John-Steinbeck-1962.jpg/440px-John-Steinbeck-1962.jpg",
      wikiUrl: "https://zh.wikipedia.org/wiki/约翰·斯坦贝克",
      searchUrl: "https://www.google.com/search?q=John+Steinbeck+1960+photo&tbm=isch"
    },
    {
      key: "charley",
      nameCn: "查理 Charley",
      nameEn: "Charles le Chien",
      caption: "一只出生在巴黎郊区、会法语的蓝灰色标准贵宾犬。斯坦贝克的「外交大使」。",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Standard_Poodle_fully_clipped.jpg/440px-Standard_Poodle_fully_clipped.jpg",
      wikiUrl: "https://en.wikipedia.org/wiki/Travels_with_Charley",
      searchUrl: "https://www.google.com/search?q=Steinbeck+Charley+poodle&tbm=isch"
    },
    {
      key: "rocinante",
      nameCn: "罗西南特 Rocinante",
      nameEn: "GMC Pickup with Camper Top",
      caption: "GMC 3/4 吨皮卡 + 定制驼背式露营车顶。名字取自堂吉诃德的马。现存于加州萨利纳斯的国家斯坦贝克中心。",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Rocinante_on_display_at_the_National_Steinbeck_Center.jpg/640px-Rocinante_on_display_at_the_National_Steinbeck_Center.jpg",
      wikiUrl: "https://en.wikipedia.org/wiki/National_Steinbeck_Center",
      searchUrl: "https://www.google.com/search?q=Steinbeck+Rocinante+truck+camper&tbm=isch"
    }
  ],

  stops: [
    {
      id: 1,
      nameCn: "萨格港",
      nameEn: "Sag Harbor, NY",
      lat: 40.9998,
      lng: -72.2926,
      time: "1960年9月底",
      timeEn: "Late September 1960",
      part: 1,
      tags: ["起点", "风暴", "准备"],
      summary: "斯坦贝克的家在长岛东端的萨格港。出发前经历了飓风唐娜（Hurricane Donna）的袭击，他冒着风暴抢救了自己的帆船 Fayre Eleyne。Rocinante 安然无恙。他带上了猎枪、钓鱼竿、书籍、打字机和足够十卷书的写作材料。Charley 在准备期间兴奋不已，躲在卡车里试图显得很小。",
      quote: "Once a journey is designed, equipped, and put in process, a new factor enters and takes over. A trip, a safari, an exploration, is an entity, different from all other journeys.",
      quoteCn: "一旦旅行被设计、装备好并启程，一个全新的因素便会介入并接管一切。一次旅行、一次探险，是一个独立的存在，不同于所有其他旅程。",
      mood: "期待与忐忑"
    },
    {
      id: 2,
      nameCn: "康涅狄格海岸",
      nameEn: "Connecticut Coast",
      lat: 41.3600,
      lng: -72.0900,
      time: "10月初",
      timeEn: "Early October 1960",
      part: 2,
      tags: ["渡轮", "对话", "出发"],
      summary: "从萨格港坐渡轮到 Shelter Island，再到 Greenport，然后从 Orient Point 坐第三趟渡轮横渡长岛海峡到康涅狄格海岸。在渡轮上遇到一个驻扎在新伦敦（New London）潜艇基地的年轻水手，聊起了核潜艇和冷战时代的生活。",
      quote: "That's the new one. She can stay down three months.",
      quoteCn: "「那是新的那艘。她能潜水三个月。」",
      mood: "新鲜好奇"
    },
    {
      id: 3,
      nameCn: "迪尔菲尔德",
      nameEn: "Deerfield, MA",
      lat: 42.5409,
      lng: -72.6073,
      time: "10月初",
      timeEn: "Early October 1960",
      part: 2,
      tags: ["家庭", "学校"],
      summary: "开到马萨诸塞州的迪尔菲尔德，看望在 Eaglebrook 寄宿学校上学的小儿子。到达太早，儿子还在睡觉。两百个十几岁的学生像朝圣一样来参观 Rocinante，让他的儿子既尴尬又骄傲。离开时特意检查车上没有偷偷藏着的逃学者。",
      quote: "My own son will probably never forgive me.",
      quoteCn: "我自己的儿子大概永远不会原谅我。",
      mood: "温情"
    },
    {
      id: 4,
      nameCn: "佛蒙特/新罕布什尔",
      nameEn: "Vermont / New Hampshire",
      lat: 43.8700,
      lng: -71.5700,
      time: "10月初",
      timeEn: "Early October 1960",
      part: 2,
      tags: ["秋叶", "对话", "政治"],
      summary: "穿过佛蒙特向北进入新罕布什尔的白山地区。新英格兰的秋叶令人震撼——红色和金黄色仿佛在燃烧。在一个农场旁扎营，和一个拥有数学博士学位的奶农深夜聊天，讨论赫鲁晓夫在联合国脱鞋敲桌子的新闻，以及即将到来的选举中人们不愿表达政治观点的沉默。",
      quote: "It is a glory, and can't be remembered, so that it always comes as a surprise.",
      quoteCn: "「这是一种荣耀，无法被记住，所以它总是像惊喜一样降临。」——一位新罕布什尔妇女说秋叶",
      mood: "惊叹"
    },
    {
      id: 5,
      nameCn: "缅因州·班戈",
      nameEn: "Bangor, Maine",
      lat: 44.8016,
      lng: -68.7712,
      time: "10月中",
      timeEn: "Mid-October 1960",
      part: 2,
      tags: ["孤独", "北极光"],
      summary: "在班戈附近一家廉价塑料汽车旅馆过夜，遇到一个了无生趣、梦想去佛罗里达过冬的女服务员。她的空洞让他感到极度孤独。那天夜里独自走出门，却看到了壮丽的北极光——玫瑰色和薰衣草色在夜空中流动。一个人美丽的自然奇观冲散了孤独。",
      quote: "A sad soul can kill you quicker, far quicker, than a germ.",
      quoteCn: "一个悲伤的灵魂能比细菌更快地杀死你，快得多。",
      mood: "孤独与惊叹"
    },
    {
      id: 6,
      nameCn: "鹿岛",
      nameEn: "Deer Isle, Maine",
      lat: 44.2240,
      lng: -68.6767,
      time: "10月中",
      timeEn: "Mid-October 1960",
      part: 2,
      tags: ["友谊", "神秘"],
      summary: "应朋友 Elizabeth Otis 的强烈要求，绕道去缅因州的鹿岛拜访 Eleanor Brace 小姐。在班戈彻底迷路，在椭圆斯沃思也迷路。鹿岛像阿瓦隆（Avalon）——一个神秘的、当你离开就会消失的地方。岛上有巨大的浣熊猫（coon cats）和世界上最好的龙虾。和一只对所有人充满仇恨的猫 George 共处了两天。",
      quote: "To put it plainly, this Isle is like Avalon; it must disappear when you are not there.",
      quoteCn: "坦白说，这座岛就像阿瓦隆；当你不在那里时，它一定会消失。",
      mood: "奇异与宁静"
    },
    {
      id: 7,
      nameCn: "缅因州北部·阿鲁斯图克县",
      nameEn: "Aroostook County, Maine",
      lat: 46.8600,
      lng: -68.0200,
      time: "10月中",
      timeEn: "Mid-October 1960",
      part: 2,
      tags: ["季节工", "法裔", "友情"],
      summary: "深入缅因州北部的土豆产区。沿美国1号公路北上经过 Houlton、Mars Hill、Presque Isle、Caribou、Van Buren，一路看到漫山遍野的土豆。在湖边遇到一群从加拿大魁北克来的法裔季节工家庭。他们用Charley当外交大使打开话题，最终九个人挤进 Rocinante，分享了一瓶珍藏的法国白兰地，度过了一个温暖的夜晚。",
      quote: "With the few divided drops of that third there came into Rocinante a triumphant human magic that can bless a house, or a truck for that matter.",
      quoteCn: "随着那第三份中寥寥几滴的分配，一种胜利的人类魔法进入了罗西南特，那种魔法能祝福一栋房子，或者一辆卡车也行。",
      mood: "温暖与人情"
    },
    {
      id: 8,
      nameCn: "兰开斯特",
      nameEn: "Lancaster, NH",
      lat: 44.4887,
      lng: -71.5695,
      time: "10月中下旬",
      timeEn: "Mid-to-Late October 1960",
      part: 2,
      tags: ["废弃", "不安"],
      summary: "从缅因州南下回到新罕布什尔。在康涅狄格河畔发现一排整洁的白色小屋和挂着“Open/Vacancy”牌子的汽车旅馆，但进去后空无一人——冰箱嗡嗡响着，水龙头滴着水，却完全没有人影。等到天黑也没人出现。这种废弃感让他深感不安，第二天一早就离开了。",
      quote: "The empty place disturbed me deeply, and, come to think of it, it still does.",
      quoteCn: "那个空无一人的地方深深地困扰了我，而且直到现在想起来仍然如此。",
      mood: "不安"
    },
    {
      id: 9,
      nameCn: "佛蒙特教堂",
      nameEn: "Vermont (Sunday Church)",
      lat: 44.0200,
      lng: -72.7400,
      time: "10月下旬",
      timeEn: "Late October 1960",
      part: 2,
      tags: ["宗教", "深刻"],
      summary: "在新英格兰的最后一天，在一个佛蒙特小镇参加了约翰·诺克斯教堂的主日礼拜。牧师先温和地安慰会众，然后突然转入一篇火与硫磺式的猛烈布道——上帝并非打垒球的老爸，而是要你下地狱的严厉法官。斯坦贝克感觉罪孽被升华了，把5美元放入了奉献盘。他在全国各地每周都去不同教堂，但再也没找到如此震撼的牧师。",
      quote: "He forged a religion designed to last, not predigested obsolescence.",
      quoteCn: "他锻造了一种经久不衰的信仰，而非预制的过时品。",
      mood: "震撼"
    },
    {
      id: 10,
      nameCn: "尼亚加拉瀑布",
      nameEn: "Niagara Falls, NY",
      lat: 43.0962,
      lng: -79.0377,
      time: "10月下旬",
      timeEn: "Late October 1960",
      part: 2,
      tags: ["迷路", "对话", "幽默"],
      summary: "进入纽约州后，在大雨中试图找到尼亚加拉瀑布。在Medina附近彻底迷路，一个喝醉的红脸男人钻进他的车，先把他骂了一顿让他扔掉地图，然后给了一堆复杂得让人记不住的指路。最终看到了瀑布——“像时代广场放大版的邦德霓虹灯”。然后决定绕道加拿大。",
      quote: "Niagara Falls is very nice. It's like a large version of the old Bond sign on Times Square.",
      quoteCn: "尼亚加拉瀑布非常好看。就像时代广场上那个老邦德广告牌的放大版。",
      mood: "幽默"
    },
    {
      id: 11,
      nameCn: "加拿大边境",
      nameEn: "Canada Border (near Buffalo)",
      lat: 42.9042,
      lng: -78.9583,
      time: "10月下旬",
      timeEn: "Late October 1960",
      part: 2,
      tags: ["官僚", "幽默", "Charley"],
      summary: "试图穿过加拿大安大略省来绕过五大湖。加拿大海关很友好，但提醒他 Charley 没有狂犬疫苗证明——美国那边不会让狗入境。来回纠缠了一番后放弃了。返回美国时反而被美国海关盘问——护照上写了电话号码，关员非常不高兴。过桥费被免了，因为收费员说“我看到你从另一边过来，我知道你会回来的。”",
      quote: "It is always the rule, the fine print, carried out by fine-print men. There's nothing to fight, no wall to hammer with frustrated fists.",
      quoteCn: "总是规则，小字条款，由小字条款的人执行。没有什么可以抗争的，没有墙可以用沮丧的拳头去捶打。",
      mood: "无奈与幽默"
    },
    {
      id: 12,
      nameCn: "伊利",
      nameEn: "Erie, Pennsylvania",
      lat: 42.1292,
      lng: -80.0851,
      time: "10月下旬",
      timeEn: "Late October 1960",
      part: 2,
      tags: ["休息", "奢侈"],
      summary: "在加拿大边境折腾一番后，来到伊利的一家豪华汽车旅馆休息。点了一份牛排和一磅生汉堡肉给 Charley，喝了苏格兰威士忌加苏打水。临睡前回想了一整天和海关官员打交道的经历，想出了许多“异常聪明犀利”的回敬话——可惜都是事后诸葛亮。",
      quote: "I overtipped mercilessly.",
      quoteCn: "我毫不留情地给了过多的小费。",
      mood: "释放"
    },
    {
      id: 13,
      nameCn: "俄亥俄/密歇根湖畔",
      nameEn: "Ohio / Northern Michigan",
      lat: 42.5000,
      lng: -83.5000,
      time: "11月初",
      timeEn: "Early November 1960",
      part: 2,
      tags: ["工业", "自然", "对话"],
      summary: "沿US-90高速公路穿越工业地带——扬斯敦（Youngstown）、克利夫兰（Cleveland）、阿克伦（Akron）、托莱多（Toledo）、庞蒂亚克（Pontiac）、弗林特（Flint），被生产的巨大规模震撼。然后开到密歇根北部的一个湖边，遇到一个看守私人领地的孤独年轻人。两人喝了威士忌，交换了谎言和友情。年轻人的妻子在城里，不喜欢乡下生活。",
      quote: "I had forgotten how rich and beautiful is the countryside—the deep topsoil, the wealth of great trees, the lake country of Michigan.",
      quoteCn: "我已经忘记了这片乡村是多么富饶和美丽——深厚的表土、茂盛的大树、密歇根的湖区。",
      mood: "反思"
    },
    {
      id: 14,
      nameCn: "芝加哥",
      nameEn: "Chicago, Illinois",
      lat: 41.8781,
      lng: -87.6298,
      time: "11月初",
      timeEn: "Early November 1960",
      part: 2,
      tags: ["妻子", "城市", "休息"],
      summary: "妻子 Elaine 从纽约飞来芝加哥短暂相聚。住在 Ambassador East 酒店。到达时全身脏兮兮穿着猎装，在大堂差点被赶走。Charley被送去宠物寄养店洗澡美容——当发现自己要被留下时，Charley 崩溃大哭。斯坦贝克通过推理酒店上一位客人留下的痕迹，推断出了“孤独哈利”（Lonesome Harry）的一整夜故事。",
      quote: "Chicago broke my continuity. This is permissible in life but not in writing.",
      quoteCn: "芝加哥打断了我的连续性。这在生活中是允许的，但在写作中不行。",
      mood: "温暖与重逢"
    },
    {
      id: 15,
      nameCn: "威斯康星",
      nameEn: "Wisconsin",
      lat: 43.7844,
      lng: -88.7879,
      time: "11月初",
      timeEn: "Early November 1960",
      part: 3,
      tags: ["田园", "奶酪", "火鸡"],
      summary: "向北穿过伊利诺伊进入威斯康星。十月的阳光下，这是一个令人窒息的美丽之地——田野、丘陵、湖泊、金黄的阳光穿透每棵被秋霜染色的树。奶酪无处不在——奶酪合作社、奶酪商店、奶酪冰淇淋。经过威斯康星河谷（Wisconsin Dells）奇特的冰河地貌。在一个卡车停靠站的山丘上，黄昏时发现整个山谷铺满了数以万计的火鸡——原来是感恩节的储备。",
      quote: "I never saw a country that changed so rapidly, and because I had not expected it everything I saw brought a delight.",
      quoteCn: "我从未见过一个变化如此迅速的地方，而因为出乎意料，我看到的一切都带来了喜悦。",
      mood: "愉悦"
    },
    {
      id: 16,
      nameCn: "双子城",
      nameEn: "Minneapolis / St. Paul, MN",
      lat: 44.9778,
      lng: -93.2650,
      time: "11月初",
      timeEn: "Early November 1960",
      part: 3,
      tags: ["迷路", "交通"],
      summary: "试图按计划穿过双子城去看密西西比河的 S 形弯道，但在交通洪流中彻底迷失。花了将近四个小时才突围出城。从未看到双子城的任何景色——只有卡车、柴油烟和交通灯。途中在密西西比河东岸一家德国餐厅停下吃饭，想去辛克莱·刘易斯的家乡索克中心。",
      quote: "I never saw St. Paul or Minneapolis. All I saw was a river of trucks; all I heard was a roar of motors.",
      quoteCn: "我从未看到圣保罗或明尼阿波利斯。我看到的只是一条卡车的河流；听到的只是引擎的轰鸣。",
      mood: "狼狈"
    },
    {
      id: 17,
      nameCn: "索克中心",
      nameEn: "Sauk Centre, Minnesota",
      lat: 45.7374,
      lng: -94.9522,
      time: "11月初",
      timeEn: "Early November 1960",
      part: 3,
      tags: ["文学", "辛克莱·刘易斯"],
      summary: "特意来到辛克莱·刘易斯（Sinclair Lewis）的家乡——《大街》（Main Street）中的原型小镇。镇上立着“辛克莱·刘易斯诞生地”的牌子。斯坦贝克回忆起晚年与刘易斯在纽约的交往——一个干瘦、孤独、不再喝酒的老人，说着“我好冷。我要去意大利了。”后来刘易斯客死意大利。小镇对他既爱又恨——活着时恨他揭露了小镇的庸俗，死后却当成旅游资源。",
      quote: "The only good writer was a dead writer. Then he couldn't surprise anyone any more, couldn't hurt anyone any more.",
      quoteCn: "唯一好的作家是死去的作家。这样他就再也不能让人意外，再也不能伤害任何人了。",
      mood: "感慨"
    },
    {
      id: 18,
      nameCn: "法戈",
      nameEn: "Fargo, North Dakota",
      lat: 46.8772,
      lng: -96.7898,
      time: "11月中",
      timeEn: "Mid-November 1960",
      part: 3,
      tags: ["传说", "地理"],
      summary: "法戈对斯坦贝克来说像撒马尔罕和大都一样充满神话色彩——从小就在报纸上看到“法戈是全大陆最冷的地方”。他把美国地图对折，法戈正好在折痕上——“美国的中缝”。到达时却发现它和其他小城没什么不同。在 Maple River 旁扎营，写了三条关于孤独的笔记，粘在番茄酱瓶上。",
      quote: "If you will take a map of the United States and fold it in the middle, eastern edge against western, and crease it sharply, right in the crease will be Fargo.",
      quoteCn: "如果你拿一张美国地图从中间对折，东边贴西边，用力折出一条线，折痕正好就是法戈。",
      mood: "神话般的失落"
    },
    {
      id: 19,
      nameCn: "恶地",
      nameEn: "Badlands, North Dakota",
      lat: 46.9000,
      lng: -103.5000,
      time: "11月中",
      timeEn: "Mid-November 1960",
      part: 3,
      tags: ["荒野", "恐惧", "美丽"],
      summary: "在俾斯麦（Bismarck）跨过密苏里河——这里是东西美国的真正分界线：河东是绿草、东部风貌；河西立刻变成褐色荒原、水蚀沟壑。恶地（Badlands）像堕落天使建造的一个与天堂作对的地方——干燥、锋利、荒凉。白天令人恐惧，夜晚却美到超乎想象——星光近在咫尺，红与银色的悬崖在落日中闪烁。遇到一个沉默寡言的栅栏边农夫和一个话多到恐怖的孤独老妇人。",
      quote: "The Badlands had become Good Lands. I can't explain it. That's how it was.",
      quoteCn: "恶地变成了好地方。我解释不了。就是这样。",
      mood: "敬畏与孤独"
    },
    {
      id: 20,
      nameCn: "蒙大拿",
      nameEn: "Montana (Billings / Livingston / Butte)",
      lat: 45.7833,
      lng: -108.5007,
      time: "11月中",
      timeEn: "Mid-November 1960",
      part: 3,
      tags: ["热爱", "购物", "方言"],
      summary: "斯坦贝克坠入了对蒙大拿的热恋。壮丽的山脉、辽阔的草原、不受电视污染的真正地方口音。在比灵斯（Billings）买了帽子，在利文斯顿（Livingston）买了夹克，在比尤特（Butte）买了一支二手雷明顿步枪和一个望远镜瞄准器。他说如果蒙大拿有海岸线，他会立刻搬过去。这是他在全美最爱的州。",
      quote: "I am in love with Montana. For other states I have admiration, respect, recognition, even some affection, but with Montana it is love.",
      quoteCn: "我爱上了蒙大拿。对其他州我有钦佩、尊重、认可，甚至有些喜爱，但对蒙大拿，是爱。",
      mood: "热恋"
    },
    {
      id: 21,
      nameCn: "小大角战场",
      nameEn: "Little Big Horn, Montana",
      lat: 45.5700,
      lng: -107.4260,
      time: "11月中",
      timeEn: "Mid-November 1960",
      part: 3,
      tags: ["历史", "凭吊"],
      summary: "在卡斯特（Custer）附近绕道南下，去凭吊小大角战场——1876年卡斯特将军和第七骑兵团全军覆没之地。摘下帽子致敬。想起老邻居 Charles Erskine Scott Wood 当年作为年轻中尉参与追击首领约瑟夫酋长（Chief Joseph）的内兹珀斯人（Nez Percés）的往事。Wood 说那是他执行过的最悲伤的任务。",
      quote: "I removed my hat in memory of brave men, and Charley saluted in his own manner.",
      quoteCn: "我摘下帽子纪念勇士们，Charley 则以他自己的方式致敬。",
      mood: "肃穆"
    },
    {
      id: 22,
      nameCn: "黄石公园",
      nameEn: "Yellowstone National Park",
      lat: 44.4280,
      lng: -110.5885,
      time: "11月中",
      timeEn: "Mid-November 1960",
      part: 3,
      tags: ["熊", "Charley", "疯狂"],
      summary: "本来对国家公园不太感兴趣，但还是拐进了黄石。结果发现了 Charley 的惊天秘密——这只一辈子对所有动物温和友善的贵宾犬，看到熊后彻底发狂：尖叫、咆哮、企图跳窗冲出去攻击体重是他一千倍的黑熊。每过一头熊就失控一次。斯坦贝克只好提前离开。公园管理员说“那狗有一颗猎熊者的心脏和灵魂”。",
      quote: "For the first time in his life Charley resisted reason, even resisted a cuff on the ear. He became a primitive killer lusting for the blood of his enemy.",
      quoteCn: "Charley 生平第一次抗拒理智，甚至抗拒了耳光。他变成了一个渴望敌人鲜血的原始杀手。",
      mood: "震惊与滑稽"
    },
    {
      id: 23,
      nameCn: "爱达荷/大分水岭",
      nameEn: "Idaho / Continental Divide",
      lat: 45.5000,
      lng: -114.0000,
      time: "11月中下旬",
      timeEn: "Mid-to-Late November 1960",
      part: 3,
      tags: ["地理", "分水岭", "雪"],
      summary: "驾车穿越爱达荷州的“上翘拇指”——真正的高山，覆盖着松树和雪。翻越大陆分水岭（Continental Divide）时特意停下来跨立在分水线上——右脚的雨水流向太平洋，左脚的流向大西洋。翻过分水岭后，空气明显变暖了，充满了来自日本暖流的太平洋气息。Charley 的膀胱问题越来越严重。",
      quote: "Rain falling on my right foot must fall into the Pacific Ocean, while that on my left foot would eventually find its way to the Atlantic.",
      quoteCn: "落在我右脚上的雨水必将流入太平洋，而落在左脚上的最终会到达大西洋。",
      mood: "壮阔"
    },
    {
      id: 24,
      nameCn: "斯波坎",
      nameEn: "Spokane, Washington",
      lat: 47.6588,
      lng: -117.4260,
      time: "11月下旬",
      timeEn: "Late November 1960",
      part: 3,
      tags: ["兽医", "Charley", "年轻人"],
      summary: "Charley 病情加重，在斯波坎找了兽医。在一个偏僻的山间小站过夜，遇到一个梦想去纽约的20岁男孩 Robbie——他正在学美发课程，他的粗犷父亲为此深感困扰。斯坦贝克巧妙地化解了父子间的尴尬，告诉他们美发师是世界上最有影响力的人。Robbie 专门给他装了一盏阅读灯。",
      quote: "It is my considered opinion that the hairdresser is the most influential man in any community.",
      quoteCn: "我经过深思熟虑后认为，美发师是任何社区中最有影响力的人。",
      mood: "幽默与温暖"
    },
    {
      id: 25,
      nameCn: "西雅图",
      nameEn: "Seattle, Washington",
      lat: 47.6062,
      lng: -122.3321,
      time: "11月下旬",
      timeEn: "Late November 1960",
      part: 3,
      tags: ["变化", "城市"],
      summary: "太平洋是他的家乡海洋——很远的内陆就闻到了海的气息。但接近西雅图时震惊于城市的巨变：他记忆中那个宁静的海港小城变成了一个疯狂扩张的怪物。山顶被削平建公寓，高速公路切割大地如冰川。在旧港区走了走——鱼市、蟹肉鸡尾酒还是老样子。Charley 的身体在休息后好转了。",
      quote: "This Seattle had no relation to the one I remembered. Set down there not knowing it was Seattle, I could not have told where I was.",
      quoteCn: "这个西雅图和我记忆中的毫无关系。如果把我放在那里但不告诉我是西雅图，我根本认不出来。",
      mood: "震惊与怅惘"
    },
    {
      id: 26,
      nameCn: "俄勒冈",
      nameEn: "Oregon Coast",
      lat: 43.8000,
      lng: -123.0000,
      time: "11月底",
      timeEn: "Late November 1960",
      part: 3,
      tags: ["爆胎", "善良"],
      summary: "在俄勒冈的大雨中，右后轮胎爆了。在八英寸深的泥水中趴在卡车下面换轮胎——手被割伤流血，满脸黄泥。备胎也有裂纹。周日所有店都关门。一个面目可怖的独眼修车站老板花了四个小时打了三个电话，发动小舅子开车去两个不同的地方找到了合适的重型轮胎。斯坦贝克说如果对人类的善良产生怀疑，就会想起这个人。",
      quote: "If ever my faith in the essential saintliness of humans becomes tattered, I shall think of that evil-looking man.",
      quoteCn: "如果我对人类本质善良的信念变得破烂不堪，我就会想起那个面目可怖的人。",
      mood: "感恩"
    },
    {
      id: 27,
      nameCn: "红杉林",
      nameEn: "Redwood Forest, Northern California",
      lat: 41.2132,
      lng: -124.0046,
      time: "12月初",
      timeEn: "Early December 1960",
      part: 3,
      tags: ["自然", "敬畏", "Charley"],
      summary: "接近南俄勒冈的红杉林地带。在一条溪流旁的草地上看到了一棵独立的巨杉祖父——三百英尺高、数千年的树龄。带 Charley 下车去朝圣，但 Charley 完全无动于衷——他连头都不抬看。斯坦贝克把他的鼻子按到树干上，但 Charley 只是走开去给一棵灌木浇水。在红杉林中住了两天——那里像大教堂，黎明和黄昏都是寂静的时刻。",
      quote: "The redwoods, once seen, leave a mark or create a vision that stays with you always. No one has ever successfully painted or photographed a redwood tree.",
      quoteCn: "红杉树一旦见过，就会留下一个印记或创造一个永远伴随你的幻象。从未有人成功地画出或拍出一棵红杉树。",
      mood: "敬畏"
    },
    {
      id: 28,
      nameCn: "萨利纳斯/蒙特雷",
      nameEn: "Salinas / Monterey, California",
      lat: 36.6777,
      lng: -121.6555,
      time: "12月初",
      timeEn: "Early December 1960",
      part: 3,
      tags: ["故乡", "变化", "政治"],
      summary: "回到出生地萨利纳斯（Salinas）和青年时代的蒙特雷（Monterey）。和姐妹们重聚，但每次聊天都不可避免地演变成关于肯尼迪和尼克松的激烈政治争吵——家人是共和党，他是民主党。在蒙特雷的 Johnny Garcia 酒吧度过了一个动人的夜晚——老友们又笑又哭，喝酒跳舞，回忆那些已故的朋友们。但Thomas Wolfe 说得对：你无法再回家。",
      quote: "Tom Wolfe was right. You can't go home again because home has ceased to exist except in the mothballs of memory.",
      quoteCn: "托马斯·沃尔夫说得对。你无法再回家了，因为家已经不存在了，除了在记忆的樟脑丸里。",
      mood: "怀旧与失落"
    },
    {
      id: 29,
      nameCn: "弗里蒙特峰",
      nameEn: "Fremont's Peak, California",
      lat: 36.7578,
      lng: -121.5050,
      time: "12月初",
      timeEn: "Early December 1960",
      part: 3,
      tags: ["告别", "风景"],
      summary: "离开前做了最后一件仪式性的事——登上弗里蒙特峰（Fremont's Peak），这是周围最高点。从这里可以俯瞰整个萨利纳斯谷、蒙特雷湾、托罗山。他小时候曾在这里钓鱼、打猎。指给 Charley 看自己童年的一切——叔叔钓鱼的小溪、母亲射杀野猫的地方、父亲在橡树上烙下爱人名字的地方。然后转身离去。",
      quote: "I printed it once more on my eyes, south, west, and north, and then we hurried away from the permanent and changeless past.",
      quoteCn: "我最后一次将它印入眼底——南、西、北——然后我们匆匆离开了那个永恒不变的过去。",
      mood: "告别"
    },
    {
      id: 30,
      nameCn: "莫哈韦沙漠",
      nameEn: "Mojave Desert, California",
      lat: 35.0525,
      lng: -117.1818,
      time: "12月初",
      timeEn: "Early December 1960",
      part: 4,
      tags: ["沙漠", "生命", "郊狼"],
      summary: "从萨利纳斯出发，经洛斯巴尼奥斯（Los Banos）、弗雷斯诺（Fresno）、贝克斯菲尔德（Bakersfield）翻山进入莫哈韦沙漠。灼热的空气、土狼般的Charley 拼命喝水。用望远镜瞄准镜看到五十码外两只郊狼——毛色金黄、柠檬黄的眼睛。准星对准了心脏，但最终没有扣下扳机。'我太老了，也太懒了，不想当一个好市民。'",
      quote: "I owned both animals. Their lives were mine. I put the safety on and laid the rifle on the table.",
      quoteCn: "我拥有了这两只动物。它们的生命属于我。我打上保险，把步枪放在桌上。",
      mood: "沉思"
    },
    {
      id: 31,
      nameCn: "亚利桑那/新墨西哥",
      nameEn: "Arizona / New Mexico",
      lat: 35.1983,
      lng: -111.6513,
      time: "12月中",
      timeEn: "Mid-December 1960",
      part: 4,
      tags: ["荒野", "疲惫"],
      summary: "从尼德尔斯（Needles）过科罗拉多河进入亚利桑那——金曼（Kingman）、阿什福克（Ash Fork）、弗拉格斯塔夫（Flagstaff）、温斯洛（Winslow）、霍尔布鲁克（Holbrook）、桑德斯（Sanders）。城镇比记忆中更亮、汽车旅馆更豪华。过了加卢普（Gallup）进入新墨西哥，在大陆分水岭上的一个小峡谷里露营。在满地威士忌空瓶的废弃营地里，给 Charley 做了生日蛋糕（四层热饼配枫糖浆）。",
      quote: "I was driving myself, pounding out the miles because I was no longer hearing or seeing.",
      quoteCn: "我在逼迫自己开车，碾过一英里又一英里，因为我已经听不到也看不到了。",
      mood: "疲惫"
    },
    {
      id: 32,
      nameCn: "阿马里洛",
      nameEn: "Amarillo, Texas",
      lat: 35.2220,
      lng: -101.8313,
      time: "12月中",
      timeEn: "Mid-December 1960",
      part: 4,
      tags: ["Charley", "兽医", "德州"],
      summary: "在一家漂亮的汽车旅馆停下。Charley 的老毛病再次发作——前列腺炎。叫来了一位开敞篷车的年轻兽医，专业、自信、温柔。确诊后需要治疗四天。Charley 立刻信任了这个人。斯坦贝克在阿马里洛停留了四天等 Charley 康复，这里开始了他对德州的长篇思考——“德州是一种精神状态”。",
      quote: "Yep. Prostatitis... It can happen to any little old boy.",
      quoteCn: "「没错。前列腺炎……任何小老头都可能得。」",
      mood: "焦虑与安心"
    },
    {
      id: 33,
      nameCn: "德州牧场",
      nameEn: "Texas Ranch (Thanksgiving)",
      lat: 31.5000,
      lng: -100.0000,
      time: "感恩节 11月底",
      timeEn: "Thanksgiving, Late November 1960",
      part: 4,
      tags: ["感恩节", "富人", "德州文化"],
      summary: "妻子从纽约飞来，一起去了一个朋友的德州牧场过感恩节。牧场巨大而美丽——人工湖、良种赫里福德牛、三只猎犬、一匹名叫 Specklebottom 的种马。有钱人穿着褪色牛仔裤和旧靴子假装朴素。感恩节的“奢华宴会”其实就是两杯威士忌、两只火鸡和一场午睡。斯坦贝克清晨去池塘钓了四条鳟鱼，用玉米粉和培根油煎了吃。",
      quote: "You got to be awful rich to dress as bad as you do.",
      quoteCn: "「你得特别有钱才能穿得像你这么差。」",
      mood: "轻松与讽刺"
    },
    {
      id: 34,
      nameCn: "穿越德州",
      nameEn: "Across Texas (Sweetwater → Beaumont)",
      lat: 30.0800,
      lng: -94.1266,
      time: "12月",
      timeEn: "December 1960",
      part: 4,
      tags: ["冰冻", "疲惫", "种族"],
      summary: "带着治好的 Charley 重新出发，冰天雪地横穿德州——斯威特沃特（Sweetwater）、巴林格（Balinger）、奥斯汀（Austin）、休斯顿（Houston）、博蒙特（Beaumont）。路面结冰，人们裹着头巾在寒风中行走。在博蒙特加油时，加油站工人看到 Charley 说了第一句种族主义笑话——这在他进入南方后反复出现。每个给他加油的人都说同一句话：“我还以为你车里坐着个黑人呢。”",
      quote: "That word seemed terribly important, a kind of safety word to cling to lest some structure collapse.",
      quoteCn: "那个词似乎极其重要，像是一个安全词，必须紧紧抓住，以免某种结构崩塌。",
      mood: "寒冷与不安"
    },
    {
      id: 35,
      nameCn: "新奥尔良",
      nameEn: "New Orleans, Louisiana",
      lat: 29.9511,
      lng: -90.0715,
      time: "12月中下旬",
      timeEn: "Mid-to-Late December 1960",
      part: 4,
      tags: ["种族隔离", "愤怒", "悲伤"],
      summary: "特意来到新奥尔良目睹了种族隔离危机中最臭名昭著的一幕——William Frantz 小学门口的“啦啦队”（Cheerleaders）。一群肥胖的白人中年妇女每天聚集在校门口，对着一个穿白裙白鞋的黑人小女孩和护送白人孩子上学的灰衣父亲，用排练好的下流话尖叫咒骂。斯坦贝克“胃里翻涌着恶心”。之后在密西西比河边坐了很久，和一个自称 Monsieur Ci Git 的南方白人绅士进行了一场关于种族问题的深刻对话。",
      quote: "I knew New Orleans, I have had many friends there, thoughtful, gentle people, with a tradition of kindness and courtesy.",
      quoteCn: "我了解新奥尔良，我在那里有许多朋友，都是体贴、温和的人，有着善良和礼貌的传统。",
      mood: "愤怒与悲伤"
    },
    {
      id: 36,
      nameCn: "归途",
      nameEn: "Return to New York",
      lat: 40.7128,
      lng: -74.0060,
      time: "12月底",
      timeEn: "Late December 1960",
      part: 4,
      tags: ["终点", "迷路", "归来"],
      summary: "从新奥尔良出发后，加速赶回纽约。不再停下来观察——旅程的吸收能力已经饱和。穿过密西西比、阿拉巴马、弗吉尼亚。最后在进入曼哈顿时，这个开了一万英里穿越三十四个州的老旅人，在自己生活了二十五年的城市里彻底迷路了。他停下来问一个警察怎么回家，警察说“你在回家之前先想想你现在在哪吧。”他回答“我知道我在哪，就是不知道怎么到这儿的。”",
      quote: "And that's how the traveler came home again.",
      quoteCn: "旅人就是这样回到了家。",
      mood: "释然"
    }
  ]
};
